###############################1
#softmax = Self_Basket_Completion(dataset="Amazon", model_type="softmax", negD=[0, 1], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="w2v", D_type="w2v")
#softmax = Self_Basket_Completion(dataset="Amazon", model_type="softmax", negD=[0, 1], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="CNN", D_type="CNN")
#base = Self_Basket_Completion(dataset="Amazon", model_type="baseline", negD=[0, 1], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="w2v", D_type="w2v")
#unif = Self_Basket_Completion(dataset="Amazon", model_type="uniform", negD=[0, 1], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="w2v", D_type="w2v")
#unifBCE = Self_Basket_Completion(dataset="Amazon", model_type="uniformBCE", negD=[0, 1], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="w2v", D_type="w2v")
#selfp = Self_Basket_Completion(dataset="Amazon", model_type="selfplay", negD=[1, 0], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="w2v", D_type="w2v")
#selfBCE = Self_Basket_Completion(dataset="Amazon", model_type="selfplayBCE", negD=[1, 0], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="w2v", D_type="w2v")
#ais = Basket_Completion(dataset="Amazon", model_type="AIS", negD=[5, 1], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="w2v", D_type="w2v")
#maligan = Basket_Completion(dataset="Amazon", model_type="MALIGAN", negD=[5, 1], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="w2v", D_type="w2v")
#base = Self_Basket_Completion(dataset="Amazon", model_type="baseline", negD=[5, 1], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="CNN", D_type="CNN")
#unif = Self_Basket_Completion(dataset="Amazon", model_type="uniform", negD=[0, 1], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="CNN", D_type="CNN")
#unifBCE = Self_Basket_Completion(dataset="Amazon", model_type="uniformBCE", negD=[0, 1], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="CNN", D_type="CNN")
#selfp = Self_Basket_Completion(dataset="Amazon", model_type="selfplay", negD=[1, 0], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="CNN", D_type="CNN")
#selfBCE = Self_Basket_Completion(dataset="Amazon", model_type="selfplayBCE", negD=[1, 0], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="CNN", D_type="CNN")
#ais = Basket_Completion(dataset="Amazon", model_type="AIS", negD=[5, 1], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="CNN", D_type="CNN")
#maligan = Basket_Completion(dataset="Amazon", model_type="MALIGAN", negD=[5, 1], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="CNN", D_type="CNN")

#base = Self_Basket_Completion(dataset="Amazon", model_type="baseline", negD=[0, 1], negG=[25,0], min_steps=2500, neg_sampled=25, G_type="w2v", D_type="w2v")
#unif = Self_Basket_Completion(dataset="Amazon", model_type="uniform", negD=[0, 25], negG=[25,0], min_steps=2500, neg_sampled=1, G_type="w2v", D_type="w2v")
#unifBCE = Self_Basket_Completion(dataset="Amazon", model_type="uniformBCE", negD=[0,25], negG=[25,0], min_steps=2500, neg_sampled=1, G_type="w2v", D_type="w2v")
#selfp = Self_Basket_Completion(dataset="Amazon", model_type="selfplay", negD=[25,0], negG=[25,0], min_steps=2500, neg_sampled=1, G_type="w2v", D_type="w2v")
#selfBCE = Self_Basket_Completion(dataset="Amazon", model_type="selfplayBCE", negD=[25,0], negG=[25,0], min_steps=2500, neg_sampled=1, G_type="w2v", D_type="w2v")
#ais = Basket_Completion(dataset="Amazon", model_type="AIS", negD=[5, 1], negG=[25,0], min_steps=2500, neg_sampled=1, G_type="w2v", D_type="w2v")
#maligan = Basket_Completion(dataset="Amazon", model_type="MALIGAN", negD=[5, 1], negG=[25,0], min_steps=2500, neg_sampled=1, G_type="w2v", D_type="w2v")
#base = Self_Basket_Completion(dataset="Amazon", model_type="baseline", negD=[5, 1], negG=[25,0], min_steps=2500, neg_sampled=25, G_type="CNN", D_type="CNN")
#unif = Self_Basket_Completion(dataset="Amazon", model_type="uniform", negD=[0,25], negG=[25,0], min_steps=2500, neg_sampled=1, G_type="CNN", D_type="CNN")
#unifBCE = Self_Basket_Completion(dataset="Amazon", model_type="uniformBCE", negD=[0,25], negG=[25,0], min_steps=2500, neg_sampled=1, G_type="CNN", D_type="CNN")
#selfp = Self_Basket_Completion(dataset="Amazon", model_type="selfplay", negD=[25,0], negG=[25,0], min_steps=2500, neg_sampled=1, G_type="CNN", D_type="CNN")
#selfBCE = Self_Basket_Completion(dataset="Amazon", model_type="selfplayBCE", negD=[25,0], negG=[25,0], min_steps=2500, neg_sampled=1, G_type="CNN", D_type="CNN")
#ais = Basket_Completion(dataset="Amazon", model_type="AIS", negD=[20, 5], negG=[25,0], min_steps=2500, neg_sampled=1, G_type="CNN", D_type="CNN")
#maligan = Basket_Completion(dataset="Amazon", model_type="MALIGAN", negD=[20, 5], negG=[25,0], min_steps=2500, neg_sampled=1, G_type="CNN", D_type="CNN")

###############################2
#softmax = Self_Basket_Completion(dataset="Belgian", model_type="softmax", negD=[0, 1], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="w2v", D_type="w2v")
#softmax = Self_Basket_Completion(dataset="Belgian", model_type="softmax", negD=[0, 1], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="CNN", D_type="CNN")
#base = Self_Basket_Completion(dataset="Belgian", model_type="baseline", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#unif = Self_Basket_Completion(dataset="Belgian", model_type="uniform", negD=[0, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#unifBCE = Self_Basket_Completion(dataset="Belgian", model_type="uniformBCE", negD=[0, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#selfp = Self_Basket_Completion(dataset="Belgian", model_type="selfplay", negD=[1, 0], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#selfBCE = Self_Basket_Completion(dataset="Belgian", model_type="selfplayBCE", negD=[1, 0], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#ais = Basket_Completion(dataset="Belgian", model_type="AIS", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#maligan = Basket_Completion(dataset="Belgian", model_type="MALIGAN", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#base = Self_Basket_Completion(dataset="Belgian", model_type="baseline", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#unif = Self_Basket_Completion(dataset="Belgian", model_type="uniform", negD=[0,25], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#unifBCE = Self_Basket_Completion(dataset="Belgian", model_type="uniformBCE", negD=[0,25], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#selfp = Self_Basket_Completion(dataset="Belgian", model_type="selfplay", negD=[1, 0], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#selfBCE = Self_Basket_Completion(dataset="Belgian", model_type="selfplayBCE", negD=[1, 0], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#ais = Basket_Completion(dataset="Belgian", model_type="AIS", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#maligan = Basket_Completion(dataset="Belgian", model_type="MALIGAN", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#base = Self_Basket_Completion(dataset="Belgian", model_type="baseline", negD=[5, 1], negG=[25,0], min_steps=10000, neg_sampled=25, G_type="w2v", D_type="w2v")
#unif = Self_Basket_Completion(dataset="Belgian", model_type="uniform", negD=[0,25], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#unifBCE = Self_Basket_Completion(dataset="Belgian", model_type="uniformBCE", negD=[0,25], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#selfp = Self_Basket_Completion(dataset="Belgian", model_type="selfplay", negD=[25,0], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#selfBCE = Self_Basket_Completion(dataset="Belgian", model_type="selfplayBCE", negD=[25,0], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#ais = Basket_Completion(dataset="Belgian", model_type="AIS", negD=[20, 5], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#maligan = Basket_Completion(dataset="Belgian", model_type="MALIGAN", negD=[20, 5], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#base = Self_Basket_Completion(dataset="Belgian", model_type="baseline", negD=[5, 1], negG=[25,0], min_steps=10000, neg_sampled=25, G_type="CNN", D_type="CNN")
#unif = Self_Basket_Completion(dataset="Belgian", model_type="uniform", negD=[0, 1], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#unifBCE = Self_Basket_Completion(dataset="Belgian", model_type="uniformBCE", negD=[0, 1], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#selfp = Self_Basket_Completion(dataset="Belgian", model_type="selfplay", negD=[25,0], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#selfBCE = Self_Basket_Completion(dataset="Belgian", model_type="selfplayBCE", negD=[25,0], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#ais = Basket_Completion(dataset="Belgian", model_type="AIS", negD=[20, 5], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#maligan = Basket_Completion(dataset="Belgian", model_type="MALIGAN", negD=[20, 5], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")

###############################3
#softmax = Self_Basket_Completion(dataset="UK", model_type="softmax", negD=[0, 1], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="w2v", D_type="w2v")
#softmax = Self_Basket_Completion(dataset="UK", model_type="softmax", negD=[0, 1], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="CNN", D_type="CNN")
#base = Self_Basket_Completion(dataset="UK", model_type="baseline", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#unif = Self_Basket_Completion(dataset="UK", model_type="uniform", negD=[0, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#unifBCE = Self_Basket_Completion(dataset="UK", model_type="uniformBCE", negD=[0, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#selfp = Self_Basket_Completion(dataset="UK", model_type="selfplay", negD=[1, 0], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#selfBCE = Self_Basket_Completion(dataset="UK", model_type="selfplayBCE", negD=[1, 0], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#ais = Basket_Completion(dataset="UK", model_type="AIS", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#maligan = Basket_Completion(dataset="UK", model_type="MALIGAN", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#base = Self_Basket_Completion(dataset="UK", model_type="baseline", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#unif = Self_Basket_Completion(dataset="UK", model_type="uniform", negD=[0, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#unifBCE = Self_Basket_Completion(dataset="UK", model_type="uniformBCE", negD=[0, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#selfp = Self_Basket_Completion(dataset="UK", model_type="selfplay", negD=[1, 0], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#selfBCE = Self_Basket_Completion(dataset="UK", model_type="selfplayBCE", negD=[1, 0], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#ais = Basket_Completion(dataset="UK", model_type="AIS", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#maligan = Basket_Completion(dataset="UK", model_type="MALIGAN", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#base = Self_Basket_Completion(dataset="UK", model_type="baseline", negD=[5, 1], negG=[25,0], min_steps=10000, neg_sampled=25, G_type="w2v", D_type="w2v")
#unif = Self_Basket_Completion(dataset="UK", model_type="uniform", negD=[0,25], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#unifBCE = Self_Basket_Completion(dataset="UK", model_type="uniformBCE", negD=[0,25], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#selfp = Self_Basket_Completion(dataset="UK", model_type="selfplay", negD=[25,0], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#selfBCE = Self_Basket_Completion(dataset="UK", model_type="selfplayBCE", negD=[25,0], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#ais = Basket_Completion(dataset="UK", model_type="AIS", negD=[20, 5], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#maligan = Basket_Completion(dataset="UK", model_type="MALIGAN", negD=[20, 5], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#base = Self_Basket_Completion(dataset="UK", model_type="baseline", negD=[5, 1], negG=[25,0], min_steps=10000, neg_sampled=25, G_type="CNN", D_type="CNN")
#unif = Self_Basket_Completion(dataset="UK", model_type="uniform", negD=[0,25], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#unifBCE = Self_Basket_Completion(dataset="UK", model_type="uniformBCE", negD=[0,25], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#selfp = Self_Basket_Completion(dataset="UK", model_type="selfplay", negD=[25,0], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#selfBCE = Self_Basket_Completion(dataset="UK", model_type="selfplayBCE", negD=[25,0], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#ais = Basket_Completion(dataset="UK", model_type="AIS", negD=[20, 5], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#maligan = Basket_Completion(dataset="UK", model_type="MALIGAN", negD=[20, 5], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")

###############################4
#softmax = Self_Basket_Completion(dataset="movielens", model_type="softmax", negD=[0, 1], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="w2v", D_type="w2v")
#softmax = Self_Basket_Completion(dataset="movielens", model_type="softmax", negD=[0, 1], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="CNN", D_type="CNN")
#base = Self_Basket_Completion(dataset="movielens", model_type="baseline", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#unif = Self_Basket_Completion(dataset="movielens", model_type="uniform", negD=[0, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#unifBCE = Self_Basket_Completion(dataset="movielens", model_type="uniformBCE", negD=[0, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#selfp = Self_Basket_Completion(dataset="movielens", model_type="selfplay", negD=[1, 0], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#selfBCE = Self_Basket_Completion(dataset="movielens", model_type="selfplayBCE", negD=[1, 0], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#ais = Basket_Completion(dataset="movielens", model_type="AIS", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#maligan = Basket_Completion(dataset="movielens", model_type="MALIGAN", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#base = Self_Basket_Completion(dataset="movielens", model_type="baseline", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#unif = Self_Basket_Completion(dataset="movielens", model_type="uniform", negD=[0, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#unifBCE = Self_Basket_Completion(dataset="movielens", model_type="uniformBCE", negD=[0, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#selfp = Self_Basket_Completion(dataset="movielens", model_type="selfplay", negD=[1, 0], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#selfBCE = Self_Basket_Completion(dataset="movielens", model_type="selfplayBCE", negD=[1, 0], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#ais = Basket_Completion(dataset="movielens", model_type="AIS", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#maligan = Basket_Completion(dataset="movielens", model_type="MALIGAN", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#base = Self_Basket_Completion(dataset="movielens", model_type="baseline", negD=[5, 1], negG=[25,0], min_steps=10000, neg_sampled=25, G_type="w2v", D_type="w2v")
#unif = Self_Basket_Completion(dataset="movielens", model_type="uniform", negD=[0,25], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#unifBCE = Self_Basket_Completion(dataset="movielens", model_type="uniformBCE", negD=[0,25], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#self = Self_Basket_Completion(dataset="movielens", model_type="selfplay", negD=[25,0], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#selfBCE = Self_Basket_Completion(dataset="movielens", model_type="selfplayBCE", negD=[25,0], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#ais = Basket_Completion(dataset="movielens", model_type="AIS", negD=[20, 5], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#maligan = Basket_Completion(dataset="movielens", model_type="MALIGAN", negD=[20, 5], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#base = Self_Basket_Completion(dataset="movielens", model_type="baseline", negD=[5, 1], negG=[25,0], min_steps=10000, neg_sampled=25, G_type="CNN", D_type="CNN")
#unif = Self_Basket_Completion(dataset="movielens", model_type="uniform", negD=[0,25], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#unifBCE = Self_Basket_Completion(dataset="movielens", model_type="uniformBCE", negD=[0,25], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#selfp = Self_Basket_Completion(dataset="movielens", model_type="selfplay", negD=[25,0], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#selfBCE = Self_Basket_Completion(dataset="movielens", model_type="selfplayBCE", negD=[25,0], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#ais = Basket_Completion(dataset="movielens", model_type="AIS", negD=[20, 5], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#maligan = Basket_Completion(dataset="movielens", model_type="MALIGAN", negD=[20, 5], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")

###############################5
#softmax = Self_Basket_Completion(dataset="netflix", model_type="softmax", negD=[0, 1], negG=[1,0], min_steps=2500, neg_sampled=1, G_type="w2v", D_type="w2v")
#softmax = Self_Basket_Completion(dataset="netflix", model_type="softmax", negD=[0, 1], negG=[1, 0], min_steps=2500, neg_sampled=1, G_type="CNN", D_type="CNN")
#base = Self_Basket_Completion(dataset="netflix", model_type="baseline", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#unif = Self_Basket_Completion(dataset="netflix", model_type="uniform", negD=[0, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#unifBCE = Self_Basket_Completion(dataset="netflix", model_type="uniformBCE", negD=[0, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#selfp = Self_Basket_Completion(dataset="netflix", model_type="selfplay", negD=[1, 0], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#selfBCE = Self_Basket_Completion(dataset="netflix", model_type="selfplayBCE", negD=[1, 0], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#ais = Basket_Completion(dataset="netflix", model_type="AIS", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#maligan = Basket_Completion(dataset="netflix", model_type="MALIGAN", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#base = Self_Basket_Completion(dataset="netflix", model_type="baseline", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#unif = Self_Basket_Completion(dataset="netflix", model_type="uniform", negD=[0, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#unifBCE = Self_Basket_Completion(dataset="netflix", model_type="uniformBCE", negD=[0, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#selfp = Self_Basket_Completion(dataset="netflix", model_type="selfplay", negD=[1, 0], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#selfBCE = Self_Basket_Completion(dataset="netflix", model_type="selfplayBCE", negD=[1, 0], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#ais = Basket_Completion(dataset="netflix", model_type="AIS", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#maligan = Basket_Completion(dataset="netflix", model_type="MALIGAN", negD=[5, 1], negG=[1, 0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#base = Self_Basket_Completion(dataset="netflix", model_type="baseline", negD=[5, 1], negG=[25,0], min_steps=10000, neg_sampled=25, G_type="w2v", D_type="w2v")
#unif = Self_Basket_Completion(dataset="netflix", model_type="uniform", negD=[0,25], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#unifBCE = Self_Basket_Completion(dataset="netflix", model_type="uniformBCE", negD=[0,25], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#selfp = Self_Basket_Completion(dataset="netflix", model_type="selfplay", negD=[25,0], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#selfBCE = Self_Basket_Completion(dataset="netflix", model_type="selfplayBCE", negD=[25,0], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#ais = Basket_Completion(dataset="netflix", model_type="AIS", negD=[20, 5], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#maligan = Basket_Completion(dataset="netflix", model_type="MALIGAN", negD=[20, 5], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="w2v", D_type="w2v")
#base = Self_Basket_Completion(dataset="netflix", model_type="baseline", negD=[5, 1], negG=[25,0], min_steps=10000, neg_sampled=25, G_type="CNN", D_type="CNN")
#unif = Self_Basket_Completion(dataset="netflix", model_type="uniform", negD=[0,25], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#unifBCE = Self_Basket_Completion(dataset="netflix", model_type="uniformBCE", negD=[0,25], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#selfp = Self_Basket_Completion(dataset="netflix", model_type="selfplay", negD=[25,0], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#selfBCE = Self_Basket_Completion(dataset="netflix", model_type="selfplayBCE", negD=[25,0], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#ais = Basket_Completion(dataset="netflix", model_type="AIS", negD=[20, 5], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")
#maligan = Basket_Completion(dataset="netflix", model_type="MALIGAN", negD=[20, 5], negG=[25,0], min_steps=10000, neg_sampled=1, G_type="CNN", D_type="CNN")